"""criar tabelas iniciais

Revision ID: f1876b4e00e9
Revises: 
Create Date: 2026-06-29 10:38:57.753956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1876b4e00e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('codigo_convite', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupos_codigo_convite'), ['codigo_convite'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('apelido', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('avaliacoes_jogador',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estrelas', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('estrelas >= 1 AND estrelas <= 5', name='ck_avaliacoes_estrelas'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_id', 'usuario_id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('local', sa.String(length=255), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status_confirmacoes', sa.String(length=20), server_default='aberto', nullable=False),
    sa.Column('cancelado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_cancelamento', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status_confirmacoes IN ('aberto', 'encerrado')", name='ck_eventos_status'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_data_evento'), ['data_evento'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_grupo_id'), ['grupo_id'], unique=False)

    op.create_table('grupo_membros',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=20), server_default='membro', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("papel IN ('admin', 'membro')", name='ck_grupo_membros_papel'),
    sa.CheckConstraint("status IN ('pendente', 'aprovado', 'rejeitado')", name='ck_grupo_membros_status'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_id', 'usuario_id')
    )
    with op.batch_alter_table('grupo_membros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupo_membros_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('historico_avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('avaliacao_anterior', sa.Integer(), nullable=True),
    sa.Column('avaliacao_nova', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_avaliacoes', schema=None) as batch_op:
        batch_op.create_index('ix_historico_avaliacoes_grupo_usuario', ['grupo_id', 'usuario_id'], unique=False)

    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=30), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('lida', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("tipo IN ('novo_evento', 'aprovacao_grupo', 'sorteio_iniciado', 'sorteio_finalizado', 'rejeicao_grupo', 'promovido_admin', 'removido_grupo')", name='ck_notificacoes_tipo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.create_index('ix_notificacoes_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_notificacoes_usuario_lida', ['usuario_id', 'lida'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('perfis_jogador',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('posicao_principal', sa.String(length=20), nullable=False),
    sa.Column('posicao_secundaria', sa.String(length=20), nullable=True),
    sa.CheckConstraint("posicao_principal IN ('Goleiro', 'Zagueiro', 'Lateral', 'Volante', 'Meio-campo', 'Meia-atacante', 'Atacante')", name='ck_perfis_posicao_principal'),
    sa.CheckConstraint("posicao_secundaria IS NULL OR posicao_secundaria IN ('Goleiro', 'Zagueiro', 'Lateral', 'Volante', 'Meio-campo', 'Meia-atacante', 'Atacante')", name='ck_perfis_posicao_secundaria'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('evento_participantes',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("resposta IN ('confirmado', 'nao_vou', 'talvez')", name='ck_evento_part_resposta'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evento_id', 'usuario_id')
    )
    with op.batch_alter_table('evento_participantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_participantes_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('sorteios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.String(length=20), nullable=False),
    sa.Column('qtd_times', sa.Integer(), nullable=False),
    sa.Column('max_jogadores_time', sa.Integer(), nullable=True),
    sa.Column('qtd_goleiros_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmado_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("modalidade IN ('aleatorio', 'balanceado')", name='ck_sorteios_modalidade'),
    sa.CheckConstraint("status IN ('pendente', 'realizado', 'confirmado')", name='ck_sorteios_status'),
    sa.CheckConstraint('qtd_times >= 2', name='ck_sorteios_qtd_times'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sorteios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sorteios_evento_id'), ['evento_id'], unique=True)

    op.create_table('times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sorteio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sorteio_id'], ['sorteios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sorteio_id', 'nome', name='uq_times_sorteio_nome'),
    sa.UniqueConstraint('sorteio_id', 'ordem', name='uq_times_sorteio_ordem')
    )
    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_times_sorteio_id'), ['sorteio_id'], unique=False)

    op.create_table('time_jogadores',
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.String(length=20), nullable=False),
    sa.Column('estrelas', sa.Integer(), server_default='3', nullable=False),
    sa.Column('eh_goleiro', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time_id', 'usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_jogadores')
    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_times_sorteio_id'))

    op.drop_table('times')
    with op.batch_alter_table('sorteios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sorteios_evento_id'))

    op.drop_table('sorteios')
    with op.batch_alter_table('evento_participantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_participantes_usuario_id'))

    op.drop_table('evento_participantes')
    op.drop_table('perfis_jogador')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_index('ix_notificacoes_usuario_lida')
        batch_op.drop_index('ix_notificacoes_created_at')

    op.drop_table('notificacoes')
    with op.batch_alter_table('historico_avaliacoes', schema=None) as batch_op:
        batch_op.drop_index('ix_historico_avaliacoes_grupo_usuario')

    op.drop_table('historico_avaliacoes')
    with op.batch_alter_table('grupo_membros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupo_membros_usuario_id'))

    op.drop_table('grupo_membros')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_eventos_data_evento'))

    op.drop_table('eventos')
    op.drop_table('avaliacoes_jogador')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupos_codigo_convite'))

    op.drop_table('grupos')
    # ### end Alembic commands ###
